/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desarrollo.tpentrega1.UI;

/**
 *
 * @author gui
 */
public class ItemsMenu extends javax.swing.JFrame {

    /**
     * Creates new form ItemsMenu
     */
    private void DisEnablePlatoFrame(boolean b){
        CaloriasField.setEnabled(b);
        PesoField.setEnabled(b);
        ApVeCheckBox.setEnabled(b);
        ApCeCheckBox.setEnabled(b);
    }
    private void DisEnableBebidaFrame(boolean b){
        GradAlcField.setEnabled(b);
        TamField.setEnabled(b);
    }
    public ItemsMenu() {
        initComponents();
        DisEnableBebidaFrame(false);
        DisEnablePlatoFrame(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        IDField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        DescripcionField = new javax.swing.JTextField();
        PrecioField = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        DescripcionLabel = new javax.swing.JLabel();
        PrecioLabel = new javax.swing.JLabel();
        CategoriaLabel = new javax.swing.JLabel();
        BebidaButton = new javax.swing.JRadioButton();
        PlatoButton = new javax.swing.JRadioButton();
        PlatoFrame = new javax.swing.JInternalFrame();
        PesoField = new javax.swing.JTextField();
        CaloriasLabel = new javax.swing.JLabel();
        AptoCeliacosLabel = new javax.swing.JLabel();
        AptoVeganosLabel = new javax.swing.JLabel();
        PesoLabel = new javax.swing.JLabel();
        ApCeCheckBox = new javax.swing.JCheckBox();
        ApVeCheckBox = new javax.swing.JCheckBox();
        CaloriasField = new javax.swing.JTextField();
        BebidaFrame = new javax.swing.JInternalFrame();
        GradAlcField = new javax.swing.JTextField();
        TamField = new javax.swing.JTextField();
        GradAlcLabel = new javax.swing.JLabel();
        TamLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de ItemsMenu");

        IDField.setText("jTextField1");

        NombreField.setText("jTextField1");

        DescripcionField.setText("jTextField1");

        PrecioField.setText("jTextField1");

        IDLabel.setText("ID");

        NombreLabel.setText("Nombre");

        DescripcionLabel.setText("Descripcion");

        PrecioLabel.setText("Precio");

        CategoriaLabel.setText("Categoria");

        buttonGroup1.add(BebidaButton);
        BebidaButton.setText("Bebida");
        BebidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidaButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(PlatoButton);
        PlatoButton.setText("Plato");
        PlatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatoButtonActionPerformed(evt);
            }
        });

        PlatoFrame.setTitle("Plato");
        PlatoFrame.setVisible(true);

        PesoField.setText("jTextField1");

        CaloriasLabel.setText("Calorias");

        AptoCeliacosLabel.setText("Apto Celiacos");

        AptoVeganosLabel.setText("Apto Veganos");

        PesoLabel.setText("Peso");

        CaloriasField.setText("jTextField1");

        javax.swing.GroupLayout PlatoFrameLayout = new javax.swing.GroupLayout(PlatoFrame.getContentPane());
        PlatoFrame.getContentPane().setLayout(PlatoFrameLayout);
        PlatoFrameLayout.setHorizontalGroup(
            PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlatoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CaloriasLabel)
                    .addComponent(AptoCeliacosLabel)
                    .addComponent(AptoVeganosLabel)
                    .addComponent(PesoLabel))
                .addGap(42, 42, 42)
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CaloriasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ApCeCheckBox)
                        .addComponent(ApVeCheckBox)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        PlatoFrameLayout.setVerticalGroup(
            PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlatoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaloriasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaloriasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AptoCeliacosLabel)
                    .addComponent(ApCeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AptoVeganosLabel)
                    .addComponent(ApVeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlatoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BebidaFrame.setTitle("Bebida");
        BebidaFrame.setVisible(true);

        GradAlcField.setText("jTextField1");

        TamField.setText("jTextField1");

        GradAlcLabel.setText("Graduacion Alcoholica");

        TamLabel.setText("Tamaño");

        javax.swing.GroupLayout BebidaFrameLayout = new javax.swing.GroupLayout(BebidaFrame.getContentPane());
        BebidaFrame.getContentPane().setLayout(BebidaFrameLayout);
        BebidaFrameLayout.setHorizontalGroup(
            BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidaFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradAlcLabel)
                    .addComponent(TamLabel))
                .addGap(42, 42, 42)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradAlcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BebidaFrameLayout.setVerticalGroup(
            BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BebidaFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradAlcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradAlcLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel)
                            .addComponent(NombreLabel)
                            .addComponent(DescripcionLabel)
                            .addComponent(PrecioLabel)
                            .addComponent(CategoriaLabel))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlatoButton)
                                .addGap(22, 22, 22)
                                .addComponent(BebidaButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlatoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BebidaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescripcionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripcionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaLabel)
                    .addComponent(BebidaButton)
                    .addComponent(PlatoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BebidaFrame)
                    .addComponent(PlatoFrame))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BebidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidaButtonActionPerformed
        DisEnableBebidaFrame(true);
        DisEnablePlatoFrame(false);
        
    }//GEN-LAST:event_BebidaButtonActionPerformed

    private void PlatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatoButtonActionPerformed
        DisEnableBebidaFrame(false);
        DisEnablePlatoFrame(true);
    }//GEN-LAST:event_PlatoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ApCeCheckBox;
    private javax.swing.JCheckBox ApVeCheckBox;
    private javax.swing.JLabel AptoCeliacosLabel;
    private javax.swing.JLabel AptoVeganosLabel;
    private javax.swing.JRadioButton BebidaButton;
    private javax.swing.JInternalFrame BebidaFrame;
    private javax.swing.JTextField CaloriasField;
    private javax.swing.JLabel CaloriasLabel;
    private javax.swing.JLabel CategoriaLabel;
    private javax.swing.JTextField DescripcionField;
    private javax.swing.JLabel DescripcionLabel;
    private javax.swing.JTextField GradAlcField;
    private javax.swing.JLabel GradAlcLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField PesoField;
    private javax.swing.JLabel PesoLabel;
    private javax.swing.JRadioButton PlatoButton;
    private javax.swing.JInternalFrame PlatoFrame;
    private javax.swing.JTextField PrecioField;
    private javax.swing.JLabel PrecioLabel;
    private javax.swing.JTextField TamField;
    private javax.swing.JLabel TamLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
