
package desarrollo.tpentrega1.UI;


import java.awt.CardLayout;
import java.awt.Dimension;

public class ItemType extends javax.swing.JPanel {

    /**
     * Creates new form ItemType
     */
    public ItemType() {
        initComponents();
        mostrarPlato();
    }
    
    public void setUIEnable(boolean e) {
        tfTamaño.setEnabled(e);
        tfGraduacionAlcoholica.setEnabled(e);
        
        tfCalorias.setEnabled(e);
        tfPeso.setEnabled(e);
        rbtnAptoCeliacos.setEnabled(e);
        rbtnAptoVegano.setEnabled(e);
        
    }
    
    public void mostrarBebida() {
        ((CardLayout)getLayout()).show(this, "card3");
        this.setMinimumSize(new Dimension(200, 150));

    }
    public void mostrarPlato() {
        ((CardLayout)getLayout()).show(this, "card2");
        this.setMinimumSize(new Dimension(200, 200));
    }
    
    public double getCalorias(){
        double d = 0;
        try {
            d = Double.parseDouble(tfCalorias.getText());
        } catch(Exception ignore){
            tfCalorias.setText("");
        }
        return d;
    }
    public void setCalorias(double cal) {
        tfCalorias.setText(cal + "");
    }
    
    public boolean getAptoVegano(){
        return rbtnAptoVegano.isSelected();
    }
    public void setAptoVegano(boolean b) {
        rbtnAptoVegano.setSelected(b);
    }
    
    public boolean getAptoCeliaco(){
        return rbtnAptoCeliacos.isSelected();
    }
    public void setAptoCeliaco(boolean b) {
        rbtnAptoCeliacos.setSelected(b);
    }
    
    public double getPeso() {
        double d = 0;
        try {
            d = Double.parseDouble(tfPeso.getText());
        } catch(Exception ignore){
            tfPeso.setText("");
        }
        return d;
    }
    public void setPeso(double p) {
        tfPeso.setText(p + "");
    }
    
    public double getTamaño() {
        double d = 0;
        try {
            d = Double.parseDouble(tfTamaño.getText());
        } catch(Exception ignore){
            tfTamaño.setText("");
        }
        return d;
    }
    public void setTamaño(double d) {
        tfTamaño.setText(d + "");
    }
    
    public double getGraduacionAlcoholica() {
        double d = 0;
        try {
            d = Double.parseDouble(tfGraduacionAlcoholica.getText());
        } catch(Exception ignore){
            tfGraduacionAlcoholica.setText("");
        }
        return d;
    }
    public void setGraduacionAlcoholica(double g) {
        tfGraduacionAlcoholica.setText(g + "");
    }
    
    public void resetCalorias() {
        tfCalorias.setText("");
    }
    public void resetPeso() {
        tfPeso.setText("");
    }
    
    public void resetTamaño() {
        tfTamaño.setText("");
    }
    public void resetGraduacionAlcoholica() {
        tfGraduacionAlcoholica.setText("");
    }
    public void resetAptoCeliacos() {
        rbtnAptoCeliacos.setSelected(true);
    }
    public void resetAptoVegano() {
        rbtnAptoCeliacos.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BebidaFrame = new javax.swing.JInternalFrame();
        GradAlcField = new javax.swing.JTextField();
        TamField = new javax.swing.JTextField();
        GradAlcLabel = new javax.swing.JLabel();
        TamLabel = new javax.swing.JLabel();
        panelBebida = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tfTamaño = new javax.swing.JTextField();
        tfGraduacionAlcoholica = new javax.swing.JTextField();
        IDLabel2 = new javax.swing.JLabel();
        NombreLabel2 = new javax.swing.JLabel();
        panelComida = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tfCalorias = new javax.swing.JTextField();
        lbCalorias = new javax.swing.JLabel();
        rbtnAptoVegano = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        tfPeso = new javax.swing.JTextField();
        lbPeso = new javax.swing.JLabel();
        rbtnAptoCeliacos = new javax.swing.JRadioButton();

        BebidaFrame.setTitle("Bebida");
        BebidaFrame.setVisible(true);

        GradAlcField.setText("jTextField1");

        TamField.setText("jTextField1");

        GradAlcLabel.setText("Graduacion Alcoholica");

        TamLabel.setText("Tamaño");

        javax.swing.GroupLayout BebidaFrameLayout = new javax.swing.GroupLayout(BebidaFrame.getContentPane());
        BebidaFrame.getContentPane().setLayout(BebidaFrameLayout);
        BebidaFrameLayout.setHorizontalGroup(
            BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidaFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradAlcLabel)
                    .addComponent(TamLabel))
                .addGap(42, 42, 42)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradAlcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BebidaFrameLayout.setVerticalGroup(
            BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BebidaFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradAlcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradAlcLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BebidaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(new java.awt.CardLayout());

        panelBebida.setLayout(new java.awt.BorderLayout());

        IDLabel2.setText("Tamaño");

        NombreLabel2.setText("Graduacion alcoholica");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IDLabel2)
                        .addComponent(NombreLabel2))
                    .addGap(42, 42, 42)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfGraduacionAlcoholica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfGraduacionAlcoholica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreLabel2))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        panelBebida.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(panelBebida, "card3");

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(220, 80));

        lbCalorias.setText("Calorias");

        rbtnAptoVegano.setText("AptoVegano");
        rbtnAptoVegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAptoVeganoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnAptoVegano)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCalorias)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(rbtnAptoVegano)
                .addGap(27, 27, 27))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCalorias))
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel6);

        panelComida.add(jPanel3);

        jPanel5.setPreferredSize(new java.awt.Dimension(221, 80));

        tfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoActionPerformed(evt);
            }
        });

        lbPeso.setText("Peso");

        rbtnAptoCeliacos.setText("AptoCeliacos");
        rbtnAptoCeliacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAptoCeliacosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbtnAptoCeliacos))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeso)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAptoCeliacos)
                .addGap(26, 26, 26))
        );

        panelComida.add(jPanel5);

        add(panelComida, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAptoCeliacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAptoCeliacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAptoCeliacosActionPerformed

    private void tfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoActionPerformed

    private void rbtnAptoVeganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAptoVeganoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAptoVeganoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame BebidaFrame;
    private javax.swing.JTextField GradAlcField;
    private javax.swing.JLabel GradAlcLabel;
    private javax.swing.JLabel IDLabel2;
    private javax.swing.JLabel NombreLabel2;
    private javax.swing.JTextField TamField;
    private javax.swing.JLabel TamLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbCalorias;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JPanel panelBebida;
    private javax.swing.JPanel panelComida;
    private javax.swing.JRadioButton rbtnAptoCeliacos;
    private javax.swing.JRadioButton rbtnAptoVegano;
    private javax.swing.JTextField tfCalorias;
    private javax.swing.JTextField tfGraduacionAlcoholica;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfTamaño;
    // End of variables declaration//GEN-END:variables
}
