/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desarrollo.tpentrega1.UI;

import java.awt.CardLayout;

/**
 *
 * @author imsac
 */
public class ItemType extends javax.swing.JPanel {

    /**
     * Creates new form ItemType
     */
    public ItemType() {
        initComponents();
        mostrarComida();
    }
    
    public void mostrarBebida() {
        ((CardLayout)getLayout()).show(this, "card3");
    }
    public void mostrarComida() {
        ((CardLayout)getLayout()).show(this, "card2");
    }
    
    public double getCalorias(){
        double d = 0;
        try {
            d = Double.parseDouble(tfCalorias.getText());
        } catch(Exception ignore){}
        return d;
    }
    public boolean getAptoVegano(){
        return rbtnAptoVegano.isSelected();
    }
    public boolean getAptoCeliaco(){
        return rbtnAptoVegano.isSelected();
    }
    public double getPeso() {
        double d = 0;
        try {
            d = Double.parseDouble(tfPeso.getText());
        } catch(Exception ignore){}
        return d;
    }
    
    public double getTamaño() {
        double d = 0;
        try {
            d = Double.parseDouble(tfTamaño.getText());
        } catch(Exception ignore){}
        return d;
    }
    
    public double getGraduacionAlcoholica() {
        double d = 0;
        try {
            d = Double.parseDouble(tfGraduacionAlcoholica.getText());
        } catch(Exception ignore){}
        return d;
    }
    
    public void resetCalorias() {
        tfCalorias.setText("");
    }
    public void resetPeso() {
        tfPeso.setText("");
    }
    
    public void resetTamaño() {
        tfTamaño.setText("");
    }
    public void resetGraduacionAlcoholica() {
        tfGraduacionAlcoholica.setText("");
    }
    public void resetAptoCeliacos() {
        rbtnAptoCeliacos.setSelected(false);
    }
    public void resetAptoVegano() {
        rbtnAptoCeliacos.setSelected(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComida = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tfCalorias = new javax.swing.JTextField();
        lbCalorias = new javax.swing.JLabel();
        rbtnAptoCeliacos = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        tfPeso = new javax.swing.JTextField();
        lbPeso = new javax.swing.JLabel();
        rbtnAptoVegano = new javax.swing.JRadioButton();
        panelBebida = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tfTamaño = new javax.swing.JTextField();
        tfGraduacionAlcoholica = new javax.swing.JTextField();
        IDLabel2 = new javax.swing.JLabel();
        NombreLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(220, 80));

        lbCalorias.setText("Calorias");

        rbtnAptoCeliacos.setText("AptoCeliacos");
        rbtnAptoCeliacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAptoCeliacosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnAptoCeliacos)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCalorias)
                    .addGap(66, 66, 66)
                    .addComponent(tfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(rbtnAptoCeliacos)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCalorias))
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel6);

        jPanel5.setPreferredSize(new java.awt.Dimension(221, 80));

        tfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoActionPerformed(evt);
            }
        });

        lbPeso.setText("Peso");

        rbtnAptoVegano.setText("AptoVegano");
        rbtnAptoVegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAptoVeganoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnAptoVegano)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeso)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnAptoVegano)
                .addGap(20, 20, 20))
        );

        jPanel3.add(jPanel5);

        panelComida.add(jPanel3);

        add(panelComida, "card2");

        IDLabel2.setText("Tamaño");

        NombreLabel2.setText("Graduacion alcoholica");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IDLabel2)
                        .addComponent(NombreLabel2))
                    .addGap(42, 42, 42)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfGraduacionAlcoholica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfGraduacionAlcoholica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreLabel2))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        panelBebida.add(jPanel4);

        add(panelBebida, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAptoCeliacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAptoCeliacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAptoCeliacosActionPerformed

    private void tfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoActionPerformed

    private void rbtnAptoVeganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAptoVeganoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAptoVeganoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel2;
    private javax.swing.JLabel NombreLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbCalorias;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JPanel panelBebida;
    private javax.swing.JPanel panelComida;
    private javax.swing.JRadioButton rbtnAptoCeliacos;
    private javax.swing.JRadioButton rbtnAptoVegano;
    private javax.swing.JTextField tfCalorias;
    private javax.swing.JTextField tfGraduacionAlcoholica;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfTamaño;
    // End of variables declaration//GEN-END:variables
}
